### ISSUE TITLE
Does this use case fit for this tool?

### ISSUE THREAD

**Issue by bigzidane** [awslabs/pocket-etl#1]
I have a XML with size <= 256kb having a below structure

```
<node>
    <id>XXX</id>
    <value1></value1>
    <value2></value2>
    <value3></value3>
    <value4></value4>
</node>
```

Now I have a requirement which I need to use id as XXX to fetch data from an Rest API and the API will return a list of data. I have to map list of returned data to fields 'value1', 'value2', ...

The API curl http://example.com/api/getById/XXX return value1=V1, value2=V2, value3=V3, value4=V4

The output will be
```
<node>
    <id>XXX</id>
    <value1>V1</value1>
    <value2>V2</value2>
    <value3>V3</value3>
    <value4>V4</value4>
</node>
```

**Comment by bmaizels** [comment]
I believe you could solve for this use-case in pocket-etl quite elegantly. If I were doing it, I would follow this implementation plan:-

1) Create an XMLStringMapper which implements Function<String, T> much like the packaged JSONStringMapper in com.amazon.pocketEtl.extractor. This mapper will allow me to create an extractor that is capable of parsing XML data.
2) Create a custom transformer where the transform method takes an object that has the id in it, makes the API call, and then decorates value1, value2, value3, value4 from the result.
3) I would create a class called XMLStringSerializer which implements StringSerializer in com.amazon.pocketEtl.loader (much like CsvStringSerializer in the same package). This serializer will allow me to create a loader that is capable of writing out my decorated objects as XML.
4) I now have all the pieces I would need to create the final job. The specifics will come down to where you are actually storing the data and where you want it to go, if the data were stored in S3 you might use an S3BufferedExtractor (leveraging the XMLStringMapper you built in step 1). The transformer in the middle would use your custom API transformer you built in step 2. If I wanted to store the final result in S3 I would use an S3FastLoader (leveraging the XMLStringSerializer I built in step 3).

If you were to build an XMLStringMapper and XMLStringSerializer that would be something that could be useful to lots of people using pocket-etl. We'd be delighted to receive and review a pull request for this functionality.

Good luck and let us know how you get on!

**Comment by bigzidane** [comment]
Thanks a lot for your support. If we compare this one with Spring Batch which includes Reader, Processor and Writer and Partitioning, what do you think about the comparison in term of performance, complexity...?

**Comment by bmaizels** [comment]
I believe you can solve your use-case with either library. A few points to consider about pocket-etl (I'm not going to comment on the pros and cons of another library on this thread):-
- Pocket-etl does not (at time of writing) have out of the box support for XML, but it's well positioned to be extended to add that functionality.
- Pocket-etl is designed with a 'cloud first' mentality and has direct integration with popular AWS services such as S3, Redshift and DynamoDB out of the box.
- Pocket-etl is designed to allow for maximum code re-usability of custom components by creating an abstraction between the job stream and the data objects being passed into and out of the components. This allows you to avoid having to layer your jobs with multiple transformers to shape the data into the correct object for that specific component to operate on and it also allows you to tunnel attributes through steps that don't operate them. This flexibility does carry a computational cost as data must be serialized and deserialized into and out of the stream at every step.
- Pocket-etl is optimized for an embedded or resource constrained runtime environment such as AWS Lambda. It has a minimal set of dependencies and avoids the use of reflection, excessive memory allocation or other known anti-patterns for this environment that contribute to long cold-start times.
- Pocket-etl does not perform orchestration of jobs and thus does not require any additional persistence or metadata storage.
- Pocket-etl is conceptually designed for single stream-based processing, not chunk or block based and it does not partition into multiple streams. The individual components of a single pocket-etl stream can be scaled independently (e.g: if you have multiple transformers calling different APIs). We have used pocket-etl for real-time stream based applications by linking it to SQS and SNS.
- Pocket-etl could be embedded as a single step in a Spring Batch job.

I hope these considerations help you decide what is best for you in your environment.
