### ISSUE TITLE
several extractors or loader or transformers is it parallel?

### ISSUE THREAD

**Issue by zivziv77** [awslabs/pocket-etl#3]
Hi

If I write several extractors, transformers or loader is it in parallel or one by one?

Thanks

Ziv

**Comment by bmaizels** [comment]
If you specify multiple extractors using either the long-form or short-form syntax, then all these extractors will run in parallel upon execution of the job and they will all stream their output to the same downstream stage:

EtlStream.extract(myextractor1, myextractor2, ...)
EtlStream.from(extract(myextractor1, myextractor2, ....)

If you wish to run multiple transformers or loaders in parallel, you should use the .withThreads() qualifier on the long-form syntax:

EtlStream.extract(myExtractor).then(load(MyClass.class, myLoader).**withThreads(5)**)

What you cannot [yet] do is load-balance between different (non-identical) transformers and loaders, to accomplish this you would have to write your own transformer or loader that wrapped other transformers/loaders and performed the load-balancing.

Note that in the example I gave above there is an expectation that your loader is threadsafe, it would need to be. If you have a non-threadsafe loader that you wish to run independent copies of (one per thread) then you can wrap your loader in the provided ParallelLoader.

Please let me know if I managed to answer your question, thanks and good luck!

**Comment by bmaizels** [comment]
Additionally, all different the components of your stream will automatically run in parallel. So, if you have a simple ETL job that is say a single extractor feeding a single transformer feeding a single loader, then when you execute the job the extract, transformer and loader will run in parallel and stream to each other as fast as they can.

Each stage has an in-memory buffer (currently hard set to 1000 records). This gives a little flexibility between the streaming parts, so an expensive SQL query extractor can get ahead of the other steps slightly. This optimization can help with the overall throughput of your job.

**Comment by zivziv77** [comment]
Hi 
Thanks for you answer it did shade some more light...

Ziv
